name: Cleanup Workspace

on:
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string
    secrets:
      token:
        required: false

jobs:
  cleanup_workspace:
    runs-on: self-hosted
    
    steps:
      - name: Clean workspace
        run: |
          echo 'Limpando WS...'
          sudo rm -rf ${{ github.workspace }}/*
