name: Sa3 Validate

on:
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string
    secrets:
      token:
        required: false

jobs:
  sa3_validate:
    name: Running Sa3 Validate
    runs-on: ubuntu-latest

    steps:
      - name: Check if on prd branch
        run: |
          if [ "$GITHUB_REF" != "refs/heads/prd" ]; then
            echo "Este workflow só ocorrerá na branch prd"
            exit 1
          fi

      - name: Zip docs folder
        run: |
          if [ -d ".github/" ]; then
            zip -v -r -p libs_pipeline.zip .github/
          else
            echo "pasta obrigatória .github não encontrada"
            exit 1
          fi

